const { test } = require('node:test')
const assert = require('node:assert/strict')
const { mkdtempSync, mkdirSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')
const { tmpdir } = require('node:os')
const { execFileSync } = require('node:child_process')
const { pushedPaths } = require('./pre-push-gate.cjs')
const { classify } = require('./pre-push-scope.cjs')

test('scopes actual new/existing branch histories without losing spaced paths', () => {
  const cwd = mkdtempSync(join(tmpdir(), 'lamprey-push-test-'))
  const git = (...args) => execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['pipe','pipe','pipe'] }).trim()
  git('init')
  git('config','user.name','Fixture')
  git('config','user.email','fixture@example.invalid')
  git('config','core.autocrlf','false')
  writeFileSync(join(cwd,'README.md'),'baseline\n')
  git('add','.')
  git('commit','-m','baseline')
  const base = git('rev-parse','HEAD')
  git('update-ref','refs/remotes/origin/main',base)
  git('symbolic-ref','refs/remotes/origin/HEAD','refs/remotes/origin/main')
  const zero = '0'.repeat(40)
  const row = (head, previous = zero) => `refs/heads/topic ${head} refs/heads/topic ${previous}\n`
  mkdirSync(join(cwd,'PLANNING'))
  writeFileSync(join(cwd,'PLANNING','with spaces.md'),'docs\n')
  git('add','.')
  git('commit','-m','docs')
  const docs = git('rev-parse','HEAD')
  assert.equal(classify(pushedPaths(row(docs),'origin',cwd)), 'docs-only')
  mkdirSync(join(cwd,'src'))
  writeFileSync(join(cwd,'src','with spaces.ts'),'product\n')
  git('add','.')
  git('commit','-m','product')
  const product = git('rev-parse','HEAD')
  assert.equal(git('status','--porcelain'), '')
  assert.deepEqual(pushedPaths(row(product,docs),'origin',cwd), ['src/with spaces.ts'])
  assert.equal(classify(pushedPaths(row(product),'origin',cwd)), 'product')
  assert.deepEqual(pushedPaths(row(zero,product),'origin',cwd), [])
  assert.throws(() => pushedPaths(row(product,'f'.repeat(40)),'origin',cwd))
  git('update-ref','--no-deref','-d','refs/remotes/origin/HEAD')
  assert.equal(classify(pushedPaths(row(product),'origin',cwd)), 'product')
  assert.deepEqual(pushedPaths('','origin',cwd), [])
  assert.throws(() => pushedPaths('broken update','origin',cwd))
})
