const { classify, isDocsPath } = require('./pre-push-scope.cjs')
const assert = require('assert')

assert.strictEqual(classify(['PLANNING/foo.md', 'DEVLOG.md']), 'docs-only')
assert.strictEqual(classify(['README.md', 'ARCHITECTURE/FUNCTION_CALLING.md']), 'docs-only')
assert.strictEqual(classify(['openwiki/tools/skills-and-plugins.md']), 'docs-only')
assert.strictEqual(classify(['NOTES.md']), 'docs-only')
assert.strictEqual(classify(['electron/ipc/chat.ts']), 'product')
assert.strictEqual(classify(['electron/ipc/chat.ts', 'PLANNING/foo.md']), 'product')
assert.strictEqual(classify(['src/App.tsx']), 'product')
assert.strictEqual(classify(['scripts/hooks/pre-push']), 'product')
assert.strictEqual(classify(['package.json']), 'product')
assert.ok(isDocsPath('graft/INDEX.md'))
assert.ok(!isDocsPath('electron/main.ts'))
console.log('pre-push-scope: ok')
