const { execFileSync } = require('node:child_process')
const { mkdirSync, writeFileSync, unlinkSync } = require('node:fs')
const { join } = require('node:path')
const assert = require('node:assert/strict')

module.exports = async function checkEnvironmentGit(app, page, profile) {
  const repo = join(profile, 'git-fixture')
  const remote = join(profile, 'git-remote.git')
  mkdirSync(repo)
  const git = (...args) => execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim()
  git('init', '-b', 'main')
  git('config', 'user.name', 'Lamprey Acceptance')
  git('config', 'user.email', 'fixture@example.invalid')
  git('config', 'core.hooksPath', join(repo, '.git', 'hooks'))
  git('commit', '--allow-empty', '-m', 'Fixture baseline')
  execFileSync('git', ['init', '--bare', remote], { stdio: 'pipe' })
  git('remote', 'add', 'origin', remote)
  git('push', '-u', 'origin', 'main')
  await app.evaluate((_electron, repo) => process.chdir(repo), repo)
  await page.reload()
  for (const surface of ['floating', 'docked']) {
    writeFileSync(join(repo, `${surface}.txt`), 'Fixture change\n')
    await page.reload()
    if (surface === 'floating') await page.getByRole('button', { name: 'Collapse panel', exact: true }).click()
    if (surface === 'docked') await page.keyboard.press('Control+Shift+e')
    const commit = surface === 'floating'
      ? page.getByRole('region', { name: 'Environment', exact: true }).getByRole('button', { name: 'Commit', exact: true })
      : page.getByRole('button', { name: 'Commit', exact: true })
    await commit.waitFor({ state: 'visible' }).catch(async (error) => { console.log(await page.locator('body').innerText()); throw error })
    const before = git('rev-parse', 'HEAD')
    await commit.click()
    const dialog = page.getByRole('dialog', { name: 'Commit changes', exact: true })
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    assert.equal(git('rev-parse', 'HEAD'), before)
    await commit.click()
    const input = dialog.getByLabel('Commit message', { exact: true })
    await input.fill(`Fixture ${surface} commit`)
    const hook = join(repo, '.git', 'hooks', 'pre-commit')
    writeFileSync(hook, '#!/bin/sh\necho "Fixture hook denied commit" >&2\nexit 1\n', { mode: 0o755 })
    await dialog.getByRole('button', { name: 'Commit', exact: true }).click()
    await page.getByText('Fixture hook denied commit', { exact: false }).waitFor()
    assert.equal(git('rev-parse', 'HEAD'), before)
    assert.equal(await input.inputValue(), `Fixture ${surface} commit`)
    unlinkSync(hook)
    await dialog.getByRole('button', { name: 'Commit', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    assert.equal(git('log', '-1', '--format=%s'), `Fixture ${surface} commit`)
    await page.getByRole('button', { name: 'Push (1 ahead)', exact: true }).click()
    await page.getByText('Pushed', { exact: true }).waitFor()
    const remoteHead = execFileSync('git', ['--git-dir', remote, 'rev-parse', 'refs/heads/main'], { encoding: 'utf8' }).trim()
    assert.equal(remoteHead, git('rev-parse', 'HEAD'))
    assert.equal(git('status', '--porcelain'), '')
    console.log(JSON.stringify({ surface, cancelledDialogPreservesHead: true, failedCommitPreservesDraft: true, realCommit: true, realPushToTemporaryLocalBareRepository: true, clean: true }))
  }
}
