/* global window, document */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { execFileSync } = require('node:child_process')

module.exports = async function contextScenario({ page, app, ids, profile, repo, providerBodies }) {
  const second = path.join(profile, 'review-second')
  const git = (...args) => execFileSync('git', args, { cwd: second, encoding: 'utf8' }).trim()
  const context = page.getByRole('button', { name: 'Task context', exact: true })
  const details = page.getByRole('dialog', { name: 'Task context details', exact: true })
  const open = async () => { await context.click(); await details.waitFor() }
  const waitPath = async expected => page.waitForFunction(expected => document.querySelector('[aria-label="Task context"]')?.getAttribute('title') === expected, expected)
  const tasks = await page.evaluate(async () => (await window.api.conversation.list()).data)
  const other = tasks.find(task => task.title === 'UX review second task')
  assert(other)
  await waitPath(repo)
  assert.equal(await page.getByRole('region', { name: 'Environment', exact: true }).count(), 0)
  assert.equal(await page.locator('.chat-column').evaluate(node => node.style.paddingRight), '')
  await app.evaluate(({ ipcMain, shell }) => {
    globalThis.uxContextClipboard = []
    globalThis.uxContextReveals = []
    globalThis.uxOriginalContextClipboard = ipcMain._invokeHandlers.get('clipboard:writeText')
    ipcMain.removeHandler('clipboard:writeText')
    ipcMain.handle('clipboard:writeText', (_event, text) => { globalThis.uxContextClipboard.push(text); return { success: true, data: null } })
    globalThis.uxOriginalShellOpenPath = shell.openPath
    shell.openPath = async value => { globalThis.uxContextReveals.push(value); return globalThis.uxFailReveal ? 'UX reveal failure' : '' }
  })
  await open()
  await details.getByRole('button', { name: 'Copy path', exact: true }).click()
  await details.getByRole('button', { name: 'Reveal folder', exact: true }).click()
  assert.deepEqual(await app.evaluate(() => globalThis.uxContextClipboard), [repo])
  assert.deepEqual(await app.evaluate(() => globalThis.uxContextReveals), [repo])
  await details.press('Escape')
  fs.writeFileSync(path.join(second, 'other.txt'), 'Context change must survive.\n')
  fs.writeFileSync(path.join(second, 'AGENTS.md'), 'UX_CONTEXT_SECOND_REPOSITORY: this is the task fixture workspace.\n')
  const dirty = git('status', '--porcelain')
  await page.getByText('UX review second task', { exact: true }).last().click()
  await waitPath(second)
  const denied = await page.evaluate(async ({ id, outside }) => window.api.files.readText(outside, id), { id: other.id, outside: path.join(repo, 'example.txt') })
  assert.equal(denied.success, false)
  const missing = await page.evaluate(async () => window.api.files.getWorkdir('missing-context-task'))
  assert.equal(missing.success, false)
  await open()
  assert.equal(await details.getByRole('button', { name: 'Change working folder', exact: true }).isDisabled(), true)
  await details.getByRole('button', { name: 'Files', exact: true }).click()
  await page.locator('#workspace-content').getByRole('button', { name: 'other.txt', exact: true }).click()
  await page.locator('#workspace-content').getByText('Context change must survive.', { exact: true }).waitFor()
  const input = page.getByRole('textbox', { name: 'Message Lamprey', exact: true })
  await input.fill('Read the current workspace instructions for this location probe.')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.getByRole('button', { name: 'Stop current turn', exact: true }).waitFor()
  for (let i = 0; i < 100 && !providerBodies.some(body => JSON.stringify(body.messages).includes('UX_CONTEXT_SECOND_REPOSITORY')); i++) await new Promise(resolve => setTimeout(resolve, 50))
  assert(providerBodies.some(body => JSON.stringify(body.messages).includes('UX_CONTEXT_SECOND_REPOSITORY')))
  await page.getByRole('button', { name: 'Stop current turn', exact: true }).click()
  await page.getByRole('button', { name: 'Send', exact: true }).waitFor()
  await open()
  await details.getByRole('button', { name: 'Switch or create branch', exact: true }).click()
  const branches = page.getByRole('dialog', { name: 'Branches', exact: true })
  await branches.getByRole('menuitem', { name: /Create and checkout new branch/ }).click()
  await branches.getByPlaceholder('branch-name', { exact: true }).fill('ux-context-branch')
  await branches.getByRole('button', { name: 'Create', exact: true }).click()
  await branches.waitFor({ state: 'hidden' })
  assert.equal(git('branch', '--show-current'), 'ux-context-branch')
  git('checkout', '-b', 'ux-external-context')
  await page.waitForFunction(() => document.querySelector('[aria-label="Task context"]')?.textContent.includes('ux-external-context'), undefined, { timeout: 25000 })
  await open()
  await details.getByRole('button', { name: 'Switch or create branch', exact: true }).click()
  await branches.getByRole('menuitem', { name: /Create and checkout new branch/ }).click()
  await branches.getByPlaceholder('branch-name', { exact: true }).fill('invalid branch name')
  await branches.getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByText(/not a valid branch name|not a valid branch/).last().waitFor()
  assert.equal(git('branch', '--show-current'), 'ux-external-context')
  assert.equal(git('status', '--porcelain'), dirty)
  await branches.press('Escape')
  await open()
  await details.getByRole('button', { name: 'Commit', exact: true }).click()
  const commit = page.getByRole('dialog', { name: 'Commit changes', exact: true })
  await commit.getByText(second, { exact: true }).waitFor()
  await commit.getByRole('button', { name: 'Cancel', exact: true }).click()
  await open()
  await app.evaluate(() => { globalThis.uxFailReveal = true })
  await details.getByRole('button', { name: 'Reveal folder', exact: true }).click()
  await page.getByText('UX reveal failure', { exact: true }).last().waitFor()
  await app.evaluate(() => { globalThis.uxFailReveal = false })
  await details.getByRole('button', { name: 'Worktree manager', exact: true }).click()
  const manager = page.getByRole('dialog', { name: 'Worktrees', exact: true })
  await manager.getByText(second.replaceAll('\\', '/'), { exact: true }).waitFor()
  const beforeWorktrees = git('worktree', 'list', '--porcelain')
  const worktree = path.join(profile, 'context-worktree')
  assert.equal(fs.existsSync(worktree), false)
  const beforeCount = (await page.evaluate(async () => (await window.api.conversation.list()).data)).length
  await manager.getByPlaceholder('branch name (e.g. feature-x)', { exact: true }).fill('ux-context-worktree')
  await manager.getByPlaceholder('path (relative resolves next to repo, or absolute)', { exact: true }).fill(worktree)
  page.once('dialog', dialog => dialog.accept())
  await manager.getByRole('button', { name: 'Create worktree', exact: true }).click()
  await manager.waitFor({ state: 'hidden' })
  await waitPath(worktree)
  const afterTasks = await page.evaluate(async () => (await window.api.conversation.list()).data)
  assert.equal(afterTasks.length, beforeCount + 1)
  assert.equal(afterTasks.filter(task => task.worktreePath === worktree).length, 1)
  assert.equal(execFileSync('git', ['status', '--porcelain'], { cwd: worktree, encoding: 'utf8' }).trim(), '')
  await page.getByText(afterTasks.find(task => task.id === other.id).title, { exact: true }).last().click()
  await waitPath(second)
  await open()
  await details.getByRole('button', { name: 'Worktree manager', exact: true }).click()
  const generatedRow = manager.getByText(worktree.replaceAll('\\', '/'), { exact: true }).locator('../..')
  page.once('dialog', dialog => dialog.accept())
  await generatedRow.getByRole('button', { name: 'remove', exact: true }).click()
  await manager.getByText(worktree.replaceAll('\\', '/'), { exact: true }).waitFor({ state: 'hidden' })
  assert.equal(fs.existsSync(worktree), false)
  assert.equal(git('worktree', 'list', '--porcelain'), beforeWorktrees)
  assert.equal(git('status', '--porcelain'), dirty)
  await manager.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByText('UX baseline task 01', { exact: true }).last().click()
  await waitPath(repo)
  const projectId = await page.evaluate(async folder => (await window.api.projects.create({ name: 'UX context project', path: folder })).data.id, second)
  await page.reload()
  await page.getByText('UX baseline task 01', { exact: true }).last().click()
  await open()
  await details.getByRole('combobox', { name: 'Task project', exact: true }).selectOption(projectId)
  await waitPath(second)
  assert.equal((await page.evaluate(async id => (await window.api.files.getWorkdir(id)).data.path, ids[1])), second)
  await details.getByRole('combobox', { name: 'Task project', exact: true }).selectOption('')
  await waitPath(repo)
  await app.evaluate(({ dialog }, folder) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [folder] }) }, second)
  await details.getByRole('button', { name: 'Change working folder', exact: true }).click()
  await waitPath(second)
  assert.equal(await page.evaluate(async () => (await window.api.files.getWorkdir()).data.path), second)
  await details.getByRole('button', { name: 'Use launch folder', exact: true }).click()
  await waitPath(repo)
  await details.press('Escape')
  await app.evaluate(({ ipcMain, shell }) => { ipcMain.removeHandler('clipboard:writeText'); ipcMain.handle('clipboard:writeText', globalThis.uxOriginalContextClipboard); shell.openPath = globalThis.uxOriginalShellOpenPath })
  return { taskAndProjectPaths: true, fileConfinement: true, modelUsesOwningAgentsFile: true, branchCreateAndExternalRefresh: true, failedBranchPreservesDirtyFiles: true, commitDialogOwnsDirectory: true, revealFailureVisible: true, worktreeCreatedSelectedAndRemoved: true, worktreeOwner: 'isolated UX fixture', worktreePurpose: 'test existing manager without dependencies or production repo changes', worktreeRetirement: 'verified clean, removed through UI, original registry restored', projectAssignment: true, folderSelectionPersisted: true, floatingSpaceRemoved: true, boundaries: 'Real Git, file processing, model request and task/project storage; clipboard, external reveal and chooser boundaries controlled; only synthetic fixture worktree created and removed.' }
}
