/* global document, getComputedStyle */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
module.exports = async function densityScenario({ page, app, ids, profile, output }) {
  const input = page.getByRole('textbox', { name: 'Message Lamprey', exact: true })
  const search = page.getByRole('searchbox', { name: 'Search tasks', exact: true })
  await search.fill('UX baseline task 38')
  await page.locator(`[data-task-id="${ids[38]}"]`).getByRole('button', { name: /^UX baseline/ }).first().click()
  await search.fill('')
  await page.waitForFunction(() => !document.querySelector('textarea[aria-label="Message Lamprey"]').disabled)
  await app.evaluate(({ BrowserWindow }) => { const win = BrowserWindow.getAllWindows()[0]; win.webContents.setZoomFactor(1); win.setContentSize(1440, 900) })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const measurements = []
  const measure = async (locator, label) => {
    const metrics = await locator.evaluate(element => {
      const rect = element.getBoundingClientRect(); const style = getComputedStyle(element)
      return { width: rect.width, height: rect.height, bottom: rect.bottom, transform: style.transform, transition: style.transitionDuration, color: style.color, background: style.backgroundColor }
    })
    assert(metrics.width >= 32 && metrics.height >= 32, `${label}: ${JSON.stringify(metrics)}`)
    assert(metrics.transition.split(',').every(value => parseFloat(value) <= 0.00001), `${label} reduced motion`)
    measurements.push({ label, ...metrics }); return metrics
  }
  for (const theme of ['Light', 'Dark']) {
    await input.focus(); await page.keyboard.press('Control+,')
    const settings = page.getByRole('dialog', { name: 'Settings', exact: true })
    await settings.getByRole('button', { name: 'Appearance', exact: true }).click()
    await settings.getByRole('button', { name: theme, exact: true }).click()
    await page.keyboard.press('Escape')
    await input.fill('UX31 control stability')
    const send = page.getByRole('button', { name: 'Send', exact: true })
    await page.getByRole('button', { name: 'Task context', exact: true }).click()
    await page.getByRole('button', { name: 'Switch or create branch', exact: true }).click()
    const branches = page.getByRole('dialog', { name: 'Branches', exact: true })
    await branches.getByRole('menuitem').first().waitFor()
    for (const row of await branches.getByRole('menuitem').all()) await measure(row, `${theme} shared branch row`)
    await page.keyboard.press('Escape')
    const taskRow = page.locator(`[data-task-id="${ids[38]}"]`)
    await taskRow.hover(); await taskRow.getByTitle('Task actions', { exact: true }).click()
    const taskMenu = page.getByRole('menu', { name: 'Task actions', exact: true })
    for (const row of await taskMenu.getByRole('menuitem').all()) await measure(row, `${theme} task menu row`)
    await page.keyboard.press('Escape')
    const before = await measure(send, `${theme} Send`)
    await page.getByRole('button', { name: 'Task context', exact: true }).click()
    await page.getByRole('button', { name: 'Review changes', exact: true }).click()
    await page.getByRole('tab', { name: 'Review', exact: true }).waitFor()
    const panelOpen = await measure(send, `${theme} panel-open Send`)
    assert(Math.abs(panelOpen.bottom - before.bottom) <= 1, 'Opening the workspace panel preserves the action baseline')
    await page.getByRole('button', { name: 'Collapse panel', exact: true }).click()
    const panelClosed = await measure(send, `${theme} panel-closed Send`)
    assert(Math.abs(panelClosed.bottom - before.bottom) <= 1, 'Closing the workspace panel restores the action baseline')
    await send.hover(); const hover = await measure(send, `${theme} Send hover`)
    assert.equal(hover.transform, 'none'); assert.equal(hover.bottom, before.bottom)
    assert.equal(await send.locator('svg').getAttribute('stroke'), 'currentColor')
    for (const label of ['Add', 'Working mode']) await measure(page.getByRole('button', { name: label, exact: true }), `${theme} ${label}`)
    await page.getByRole('button', { name: 'Add', exact: true }).click()
    const menu = page.getByRole('menu', { name: 'Add to prompt', exact: true })
    for (const button of await menu.getByRole('button').all()) await measure(button, `${theme} Add item ${await button.innerText()}`)
    await page.keyboard.press('Escape')
    const note = path.join(profile, 'ux31-note.txt'); fs.writeFileSync(note, 'Control density attachment')
    await app.evaluate(({ dialog }, note) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [note] }) }, note)
    await page.getByRole('button', { name: 'Add', exact: true }).click()
    await page.getByRole('button', { name: /Add files or photos/ }).click()
    await page.getByText('ux31-note.txt', { exact: true }).waitFor()
    const attached = await measure(send, `${theme} attachment Send`)
    assert(Math.abs(attached.bottom - before.bottom) <= 1, 'Attachment should grow above the anchored controls')
    await page.getByTitle('Remove attachment', { exact: true }).click()
    await send.click()
    const stop = page.getByRole('button', { name: 'Stop current turn', exact: true }); await stop.waitFor()
    const running = await measure(stop, `${theme} Stop`)
    assert(Math.abs(running.bottom - before.bottom) <= 1, 'Status changes retain the action baseline')
    await stop.hover(); assert.equal((await measure(stop, `${theme} Stop hover`)).transform, 'none')
    const bytes = await app.evaluate(async ({ BrowserWindow }) => Array.from((await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG()))
    fs.writeFileSync(path.join(output, `${theme.toLowerCase()}-controls.png`), Buffer.from(bytes))
    await stop.click(); await send.waitFor()
  }
  return { measurements, reducedMotion: true, realAttachment: true, actualStreamAndStop: true }
}
