/* global window, document */
const assert = require('node:assert/strict')
module.exports = async function historyScenario({ page, ids, providerBodies, finishStreams }) {
  const input = page.getByRole('textbox', { name: 'Message Lamprey', exact: true })
  const stop = page.getByRole('button', { name: 'Stop current turn', exact: true })
  const activity = page.getByRole('button', { name: 'Tool activity', exact: true })
  const dialog = page.getByRole('dialog', { name: 'Turn activity', exact: true })
  const select = async id => {
    const expand = page.getByRole('button', { name: 'Expand sidebar', exact: true })
    if (await expand.isVisible()) await expand.click()
    const title = await page.evaluate(async id => (await window.api.conversation.list()).data.find(task => task.id === id).title, id)
    await page.getByText(title, { exact: true }).last().click()
    await page.waitForFunction(() => !document.querySelector('textarea[aria-label="Message Lamprey"]').disabled)
  }
  await select(ids[0]); await activity.click()
  const group = dialog.locator('[data-tool-group-id="group:ux-tool-0"]')
  await group.locator(':scope > button').click()
  const card = group.locator('[data-tool-call-id="ux-tool-5"]')
  await card.locator(':scope > button').click()
  await card.getByText('Before review', { exact: true }).waitFor()
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await input.fill('UX18 history retained during ordinary streaming')
  await page.getByRole('button', { name: 'Send', exact: true }).click(); await stop.waitFor()
  await activity.click()
  assert.equal(await group.locator(':scope > button').getAttribute('aria-expanded'), 'true')
  assert.equal(await card.locator(':scope > button').getAttribute('aria-expanded'), 'true')
  assert.equal(await dialog.locator('[data-tool-call-id]').count(), 200)
  const scroll = dialog.locator('[data-tool-history-scroll]')
  await scroll.evaluate(node => { node.scrollTop = 250 })
  const before = await scroll.evaluate(node => node.scrollTop)
  await page.waitForTimeout(500)
  assert.equal(await scroll.evaluate(node => node.scrollTop), before)
  await dialog.getByRole('button', { name: 'Close', exact: true }).click(); await stop.click()
  await select(ids[20])
  await page.getByTitle('Switch model', { exact: true }).click()
  const models = page.getByRole('menu', { name: 'Models', exact: true })
  await models.getByRole('searchbox', { name: 'Search models', exact: true }).fill('fixture-vision')
  await models.locator('[data-model-id="fixture-vision"]').click()
  const callIds = []
  for (const kind of ['success', 'failure', 'denied']) {
    const count = providerBodies.length
    await input.fill(`UX16 approval fixture UX18 ${kind}`)
    await page.getByRole('button', { name: 'Send', exact: true }).click()
    const approval = page.getByRole('dialog', { name: 'Allow this action?', exact: true }).or(page.locator('[data-inline-approval]'))
    await approval.waitFor()
    await approval.getByRole('button', { name: kind === 'denied' ? /^(2 )?Deny$/ : /^(Allow|1 Approve)$/ }).click()
    await page.waitForFunction(async ({ owner, count }) => {
      const rows = (await window.api.tools.getCallsForConversation(owner)).data
      return rows.length === count && rows.every(row => ['done', 'error', 'denied'].includes(row.status))
    }, { owner: ids[20], count: callIds.length + 1 })
    for (let i = 0; i < 100 && providerBodies.length < count + 2; i++) await new Promise(resolve => setTimeout(resolve, 50))
    finishStreams()
    await page.locator('[data-task-status="Completed"]').waitFor()
    const rows = await page.evaluate(async id => (await window.api.tools.getCallsForConversation(id)).data, ids[20])
    const latest = rows[0]; callIds.push(latest.id)
    assert.equal(latest.status, kind === 'success' ? 'done' : kind === 'failure' ? 'error' : 'denied')
  }
  await page.reload(); await select(ids[20]); await activity.click()
  await dialog.locator(`[data-tool-call-id="${callIds[0]}"][data-tool-outcome="success"]`).waitFor()
  assert.deepEqual(await dialog.locator('[data-tool-call-id]').evaluateAll(nodes => nodes.map(node => node.dataset.toolCallId)), callIds)
  const success = dialog.locator(`[data-tool-call-id="${callIds[0]}"]`)
  await success.locator(':scope > button').click()
  assert((await success.textContent()).includes('UX18-END'))
  assert((await success.textContent()).length > 4096)
  assert.equal(await dialog.locator(`[data-tool-call-id="${callIds[1]}"]`).getAttribute('data-tool-outcome'), 'error')
  assert.equal(await dialog.locator(`[data-tool-call-id="${callIds[2]}"]`).getAttribute('data-tool-outcome'), 'denied')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  return { seededCalls: 200, retainedAcrossNewTurn: true, expansionAndScrollStableDuringStreaming: true, realMixedOutcomes: ['success', 'error', 'denied'], chronologicalAfterReload: true, fullResultBeyond4096Recovered: true }
}
