/* global window, document */
const assert = require('node:assert/strict')
module.exports = async function modelScenario({ page, providerBodies }) {
  const trigger = page.getByTitle('Switch model', { exact: true })
  const menu = page.getByRole('menu', { name: 'Models', exact: true })
  const search = menu.getByRole('searchbox', { name: 'Search models', exact: true })
  const keyed = menu.locator('[data-model-id="fixture-keyed-model"]')
  const local = menu.locator('[data-model-id="fixture-stream"]')
  await trigger.click()
  await search.fill('no-such-fixture-model')
  await menu.getByText('No matching models.', { exact: true }).waitFor()
  await search.fill('fixture-keyed')
  await keyed.getByText('Add key', { exact: true }).waitFor()
  await keyed.click()
  const setup = page.getByRole('dialog', { name: 'Add a Fixture Keyed Provider API key', exact: true })
  await setup.waitFor()
  await setup.locator('input[type="password"]').fill('fixture-provider-key')
  page.once('dialog', dialog => dialog.accept())
  await setup.getByRole('button', { name: 'Connect', exact: true }).click()
  await setup.waitFor({ state: 'hidden' })
  await trigger.click()
  await search.fill('fixture-keyed')
  await keyed.getByText('Key stored', { exact: true }).waitFor()
  await search.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  assert.equal(await keyed.evaluate(node => node === document.activeElement), true)
  await page.keyboard.press('Enter')
  await menu.waitFor({ state: 'hidden' })
  assert.match(await trigger.innerText(), /deliberately long display name/)
  assert.equal((await page.evaluate(async () => window.api.model.getActive())).data, 'fixture-keyed-model')
  await page.getByRole('textbox', { name: 'Message Lamprey', exact: true }).fill('Verify keyed model routing in this local fixture.')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.getByRole('button', { name: 'Stop current turn', exact: true }).waitFor()
  for (let i = 0; i < 100 && !providerBodies.some(body => body.model === 'fixture-keyed-model' && body._fixtureKeyAccepted); i++) await new Promise(resolve => setTimeout(resolve, 50))
  assert(providerBodies.some(body => body.model === 'fixture-keyed-model' && body._fixtureKeyAccepted))
  await page.getByRole('button', { name: 'Stop current turn', exact: true }).click()
  await page.getByRole('button', { name: 'Send', exact: true }).waitFor()
  await trigger.click()
  const selectedVisible = await keyed.evaluate(node => { const row = node.getBoundingClientRect(); const parent = node.parentElement.getBoundingClientRect(); return row.top >= parent.top && row.bottom <= parent.bottom })
  assert(selectedVisible)
  await menu.press('Escape')
  const deleted = await page.evaluate(async () => window.api.settings.deleteProviderKey('fixture-keyed'))
  assert(deleted.success)
  await trigger.click()
  await search.fill('fixture-keyed')
  await keyed.getByText(/Add key/).waitFor()
  await menu.getByRole('button', { name: /All models/ }).click()
  await menu.getByText('No matching models.', { exact: true }).waitFor()
  await search.fill('fixture-stream')
  await local.getByText('No key needed', { exact: true }).waitFor()
  await local.click()
  assert.equal((await page.evaluate(async () => window.api.model.getActive())).data, 'fixture-stream')
  const saved = await page.evaluate(async () => window.api.settings.saveProviderKey('fixture-keyed', 'fixture-provider-key'))
  assert(saved.success)
  await trigger.click()
  await search.fill('fixture-keyed')
  await keyed.getByText('Key stored', { exact: true }).waitFor()
  await menu.getByRole('button', { name: /Ready to use only/ }).click()
  await menu.press('Escape')
  assert.equal(await trigger.evaluate(node => node === document.activeElement), true)
  return { catalogSearchAndEmpty: true, keylessSelection: true, realLocalKeySetupAndAuthentication: true, configuredSelectionAndRouting: true, longLabelBounded: true, selectedRowRevealed: true, keyboardSelectionAndEscapeFocus: true, externalKeyDeletionAndSaveRefresh: true, fullCatalogAccessible: true, boundary: 'Built Electron renderer/preload/main and actual loopback /models authentication plus keyed chat request. Synthetic credential exists only in disposable profile; zero external provider requests.' }
}
