/* global window, document */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { execFileSync } = require('node:child_process')

module.exports = async function reviewScenario({ page, app, ids, profile, repo, switchTask }) {
  const second = path.join(profile, 'review-second')
  fs.mkdirSync(second)
  const git = (...args) => execFileSync('git', args, { cwd: second, encoding: 'utf8' })
  git('init')
  git('config', 'user.name', 'UX fixture')
  git('config', 'user.email', 'fixture@example.invalid')
  fs.writeFileSync(path.join(second, 'other.txt'), 'Second before\n')
  git('add', 'other.txt')
  git('commit', '-m', 'Fixture initial')
  fs.writeFileSync(path.join(second, 'other.txt'), 'Second after\n')
  const otherId = await page.evaluate(async folder => {
    const result = await window.api.conversation.create('fixture-stream', { kind: 'worktree', worktreePath: folder })
    if (!result.success) throw new Error(result.error)
    await window.api.conversation.updateTitle(result.data.id, 'UX review second task')
    await window.api.conversation.appendSystem(result.data.id, 'UX second review ready.')
    return result.data.id
  }, second)
  await page.reload()
  await page.getByTitle('Switch model', { exact: true }).waitFor()
  await switchTask('UX baseline task 01', 'Baseline alternate task ready.')
  const open = async () => page.getByRole('button', { name: 'Review task changes', exact: true }).click()
  await open()
  const content = page.locator('#workspace-content')
  await content.getByRole('button', { name: 'example.txt', exact: true }).click()
  await content.getByText('+After review', { exact: true }).waitFor()
  await content.getByRole('button', { name: 'Fix this →', exact: true }).click()
  const input = page.locator('.chat-column textarea').first()
  assert((await input.inputValue()).includes('example.txt'))
  assert((await input.inputValue()).includes('@@'))
  assert.equal(await page.getByRole('tab', { name: 'Review', exact: true }).count(), 1)
  await input.fill('')
  await content.getByTitle('Stage', { exact: true }).first().click()
  await content.getByTitle('Unstage', { exact: true }).waitFor()
  assert(execFileSync('git', ['diff', '--cached', '--name-only'], { cwd: repo, encoding: 'utf8' }).includes('example.txt'))
  await content.getByText('+After review', { exact: true }).waitFor()
  await content.getByTitle('Unstage', { exact: true }).click()
  await content.getByTitle('Stage', { exact: true }).first().waitFor()
  await page.getByText('UX review second task', { exact: true }).last().click()
  await page.getByText('UX second review ready.', { exact: true }).waitFor()
  await open()
  await content.getByRole('button', { name: 'other.txt', exact: true }).click()
  await content.getByText('+Second after', { exact: true }).waitFor()
  assert.equal(await content.getByRole('button', { name: 'example.txt', exact: true }).count(), 0)
  const resolved = await page.evaluate(async id => (await window.api.review.status({ conversationId: id })).data.cwd, otherId)
  assert.equal(path.resolve(resolved), path.resolve(second))
  const missing = await page.evaluate(async () => window.api.review.status({ conversationId: 'missing-review-task' }))
  assert.equal(missing.success, false)
  assert(missing.error.includes('no longer exists'))
  git('add', 'other.txt'); git('commit', '-m', 'Fixture clean')
  await content.getByTitle('Refresh', { exact: true }).click()
  await content.getByText('No changes — clean working tree.', { exact: true }).waitFor()
  await switchTask('UX baseline task 06', 'UX terminal task B ready.')
  await open()
  await content.getByRole('alert').waitFor()
  assert.equal(await content.getByText('No changes — clean working tree.', { exact: true }).count(), 0)
  await switchTask('UX baseline task 01', 'Baseline alternate task ready.')
  await content.getByText('+After review', { exact: true }).waitFor()
  const metadata = await page.evaluate(id => JSON.parse(localStorage.getItem('lamprey.ui.workspaces'))[JSON.stringify([id])], ids[1])
  assert.deepEqual(metadata.reviewSelection, { path: 'example.txt', staged: false })
  await require('./pull-requests.cjs')(app, page)
  await page.getByRole('dialog', { name: 'Settings', exact: true }).getByRole('button', { name: 'Close settings', exact: true }).click()
  await app.evaluate(({ ipcMain }) => {
    globalThis.uxPrBindings = []
    ipcMain.removeHandler('github:bindPullRequest')
    ipcMain.handle('github:bindPullRequest', (_event, ...args) => { globalThis.uxPrBindings.push(args); return { success: true, data: true } })
  })
  await content.getByRole('button', { name: 'Pull requests', exact: true }).click()
  await content.getByRole('button', { name: /Fixture pull request/ }).click()
  await content.getByRole('button', { name: 'Send hunk', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.chat-column textarea')?.value.includes('fixture.ts'))
  assert((await input.inputValue()).includes('b'.repeat(40)))
  assert.equal(await page.getByRole('tab', { name: 'Review', exact: true }).count(), 1)
  const bindings = await app.evaluate(() => globalThis.uxPrBindings)
  assert(JSON.stringify(bindings).includes(ids[1]))
  return { taskDirectory: resolved, stageUnstage: true, cleanAndNoRepository: true, selectionRestored: true, localAndPrFeedbackInOwningComposer: true, githubBoundary: 'controlled IPC fixture; zero remote writes' }
}
